services:
  app:
    build: ..
    hostname: app
    networks:
      - ingress
    volumes:
      - $PWD/data:/data
      - $PWD/../:/app-dev
    working_dir: /app-dev
    user: '1000:1000'
    environment:
      ADMINS: group:admin
      NODE_ENV: ''
    command: "sh -c 'npm install && npm run dev'"

  proxy:
    image: caddy:alpine
    networks:
      - ingress
    volumes:
      - $PWD/Caddyfile.dev:/etc/caddy/Caddyfile:ro
    ports:
      - "8080:8080"

networks:
  ingress: